Write a Shell script that runs Python code.

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,14 @@
 #!/bin/bash
 
+# Check check for errors
+if [ -z "$PYFILE" ]; then
+  echo "PYFILE environment variable not set"
+  exit 1
+fi
+
+if [ ! -f "$PYFILE" ]; then
+  echo "Python file $PYFILE not found"
+  exit 1
+fi
+
 python "$PYFILE"
